- name: Delete default Istio Ingress Gateway
  shell:
    kubectl delete --ignore-not-found=true -n istio-system deployment,svc istio-ingressgateway
  tags:
    - never
    - apply


- name: Apply custom Istio IngressGateway
  k8s:
    state: present
    # definition: "{{ lookup('template', 'ingressgw-' + k8s_istio_version_canonical + '.yml.j2' }}"
    definition: "{{ lookup('template', k8s_istio_ingressgw_custom + '-' + k8s_istio_version_canonical + '.yml.j2') }}"
  tags:
    - never
    - apply


- name: Delete custom Istio IngressGateway
  k8s:
    state: absent
    # definition: "{{ lookup('template', 'ingressgw-' + k8s_istio_version_canonical + '.yml.j2' }}"
    definition: "{{ lookup('template', k8s_istio_ingressgw_custom + '-' + k8s_istio_version_canonical + '.yml.j2') }}"
  tags:
    - never
    - delete
